version: '2.0'

services:
  server:
    container_name: server
    build: ./server/src
    image: server:latest
    ports:
      - 12345:12345
    volumes:
      - ./server/src:/code
    depends_on:
      - postgres
      
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_DB=stock_market
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ece568hw4
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 5432:5432
    volumes:
      #- ./postgres-data:/var/lib/postgresql/data
      # copy sql script to create tables
      - ./dbinit.sql:/docker-entrypoint-initdb.d/create_tables.sql
