/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece568.em.client;

import edu.duke.ece568.em.common.Thing;


public class Client{
  public int sum(int n){
    int ans = 0;
    while (n > 0){
      ans = ans + n;
      n--;
    }
    return ans;
  }
  public static void main(String[] args) {
    Thing t = new Thing("client");
    System.out.println(t); 
  }
}









